### ISSUE TITLE
URGENT:  Do not allow NPL serial numbers with a hyphen to flow either 1 or 2 way sync

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#275]
For example, NPL-1, NPL-2, NPL-3.

These are not true reference.  Instead, they are means of communication between our customer and us when they need to provide us large PDFs that they cannot email.

**Comment by ntgn81** [comment]
Can you test this, please?

**Comment by JulieJager** [comment]
@ntgn81 I tested in Prod & Dev and they still flow.
See:
novelip.com
SPC-TEST2

**Comment by ntgn81** [comment]
Oh, I didn't realize it can be anything, not just NPL. So anything with a dash does not flow? Would that be too generic?

**Comment by JulieJager** [comment]
Oh dear.  I think I confused you.  It is just SyncIDS NPL serial numbers  with a hyphen.  When I created Test2 and two-way synced to a group, none of the NPL-s should have flowed into it. 

None of these should be in Test2. 
![capture](https://cloud.githubusercontent.com/assets/17907226/16066535/c5421bee-3279-11e6-9e8b-01792d4a9beb.JPG)

**Comment by ntgn81** [comment]
@JulieJager , could you please give it a try? I believe I had a fix for it.

**Comment by JulieJager** [comment]
@ntgn81 This is not working properly yet.  I received two report of this happening with our beta testers today. Sorry I didn't test previously.

**Comment by ntgn81** [comment]
@JulieJager , should be fixed now. Can you give it another try, please?

**Comment by JulieJager** [comment]
@ntgn81 Great!  Unfortunately, I still do not know how it was happening so testing is difficult.

**Comment by ntgn81** [comment]
@JulieJager , you can go to syncids.com DB. Client `test`. All matters in that client have `NPL-1` and `NPL2`. Create a new matter, oneway sync that from `002`, you shouldn't see 2 NPLs in the new matter, just one.
